### PR TITLE
Various changes and fixes

### LINKED ISSUE #60: h5lock is private
Like we discussed, I wrote my own attribute reader because it's still not supported. Everything went OK, until I tried to use `h5lock` to make my low-level calls sync with the library. That didn't work from the outside, and I got the error:
```
error[E0603]: module `sync` is private
 --> <::hdf5::macros::h5lock macros>:5:53
  |
5 | ] # [ allow ( unused_unsafe ) ] unsafe { $ crate :: sync :: sync ( || $ expr )
  |                                                     ^^^^
```
Can you please make `sync` it public?

### LINKED ISSUE #74: ndarray 0.13 support
Hi,

Thanks for creating this crate, it is fantastic!

Could the dependency on ndarray be relaxed so both 0.12 and 0.13 of this crate can be supported? Not a big issue, but it took me some time to figure out that I mixed ndarray crate versions in my application.

Regards,
Windel

### PR DESCRIPTION
**Pull request by aldanor**
Closes #60 
Closes #74 
Closes #78 

This is a collection of various changes, fixes and version bumps accumulated over time in the feature/dcpl branch (see update changelog for details).

### CODE REVIEW

**Comment by kalcutter** [comment]
It appears that ndarray 0.13 doesn't support Rust 1.36. Can you just bump the minimum required Rust version and update the ci pipeline?
See also: https://stackoverflow.com/questions/58175119/rust-package-using-unstable-library-feature-iter-nth-back

**Comment by kalcutter** [comment]
Can you also please include minor fix #77 in this release?

**Comment by aldanor** [comment]
Yea, I'll include #77 and a few other fixes that accumulated.

Thanks for looking into ndarray - I guess we'll bump the minimum required version and I'll updated the CI configs.

**Comment by aldanor** [comment]
I wonder why Travis builds no longer show up here on GitHub... (despite the builds actually running)

**Pull request merged**
