### PR TITLE
Update hdf5-src to use 1.10.7

### LINKED ISSUE #153: Cannot compile hdf5-src on macos
It fails with
```shell
H5Fsuper.c:1397:16: error: implicit declaration of function
'H5O__fsinfo_set_version' is invalid in C99
[-Werror,-Wimplicit-function-declaration]
             if(H5O__fsinfo_set_version(f, &fsinfo) < 0)
```
The solution is to add 
```
-D CMAKE_C_FLAGS="-Wno-error=implicit-function-declaration"
```
to cmake.

### PR DESCRIPTION
**Pull request by mulimoen**
This version is mostly a maintaince release, but introduces some new functions for allocation information which might be of use.

Fixes #153

### CODE REVIEW

**Review by aldanor — APPROVED** [review]

**Comment by aldanor** [comment]
Changelog? (for both adding the apis and for changing the default version for hdf5-src)

**Comment by aldanor** [comment]
> Merge gone wrong, fixed

👍

**Comment by mulimoen** [comment]
This is a bit tricky without a windows computer... I think the `libz` that is built has a different name on `msvc`, but I am not sure how to find this. I've opened an issue (https://github.com/rust-lang/libz-sys/issues/80) to get this name through env inspection instead.

**Comment by mulimoen** [comment]
Turns out a `hdf5-c` utility was being built, and tried to link to `libz`. Why this did not fail on other platforms is a mystery. Perhaps all other platforms includes some `libz` by default?

**Pull request merged**
