### PR TITLE
Switch to GitHub Actions, add MPI tests

### PR DESCRIPTION
**Pull request by aldanor**
- Switch all CI testing entirely to GitHub Actions
- Expand testing matrix, now 24 various builds are running (under 10m runtime total)
- Run scheduled daily tests to see if anything breaks under nightly
- Remove Travis / AppVeyor configs
- Update README badges and some outdated info, add link to docs.rs (next release if it works out)
- Actually test `--features=mpio`, apt and conda-forge, OpenMPI and MPICH (that took a while to figure out, particularly with conda one)
- Fix a bunch of clippy errors; cargo clippy and cargo fmt also run on CI

This is currently blocked by #104 (reproducible crash on Windows) – if anyone with a windows box wants to help out, yw. If it turns out to be a known bug or something, we can mention it in readme and exclude it from CI.

### CODE REVIEW

**Comment by magnusuMET** [comment]
It would be preferable to have the `lints` job on top of the list of jobs to run. It might also be a good idea to run `cargo doc` to ensure documentation is kept up to date.

**Comment by magnusuMET** [comment]
We could split the crater runs from the regular CI by creating a separate `.yml` that only runs as a `cron` job.

**Comment by aldanor** [comment]
> We could split the crater runs from the regular CI by creating a separate `.yml` that only runs as a `cron` job.

Yes, that was my plan. A bit unfortunate that a lot will have to be copied/pasted, of course.

**Comment by aldanor** [comment]
@magnusuMET Moved lints up, there's not much to check now really, but I have big docs work/rework in mind later this year (especially if we manage to build docs.rs docs), will revise it then.

This whole endeavour seems to have been well worth it since it allowed us to discover and fix #104 :)

**Pull request merged**
