### PR TITLE
Find the default HDF5 location in Fedora Linux

### PR DESCRIPTION
**Pull request by jneuff**
This solves issue 39.

### CODE REVIEW

**Comment by SuperFluffy** [comment]
This looks like fedora specific issue, not something that's related to how hdf5 itself is build or distributed.

I am not the maintainer, but I would personally not be in favor of merging distribution specific fixes.

**Comment by jneuff** [comment]
> This looks like fedora specific issue, not something that's related to how hdf5 itself is built or distributed.
> 
> I am not the maintainer, but I would personally not be in favor of merging distribution specific fixes.

Generally, I agree with you. However, I am not sure about the reasons why HDF ist not picked up via pkg-conf. There seems to be a similar problem in Ubuntu, for which `hdf5-sys` already contains a fix. So the maintainer already went down that road, probably for a reason.

Let's hear some more opinions on this.

**Comment by SuperFluffy** [comment]
Good to know, thanks.

**Comment by aldanor** [comment]
Don't mind having Fedora-specific paths in the build script if it helps anyone. After all, the build script is one big hack (by purpose) and already contains Ubuntu-specific paths and macOS/Homebrew-specific stuff anyway, the point being it's expected to "just work" in most common setups which I believe it does (Fedora aside).

Two questions though:

- Why `H5pubconf-64.h`? First time I'm seeing this; is this a Fedora specific thing or an HDF5 one?
- Why does pkg-config method fail? Might be useful to know. Could you e.g. dump its output (from the build script) to check what it says?

// Ignore the nightly test failures; unrelated (to be fixed later)

**Comment by jneuff** [comment]
>     * Why `H5pubconf-64.h`? First time I'm seeing this; is this a Fedora specific thing or an HDF5 one?
>

It seems to be a Fedora thing. Fedora 29 ships HDF 1.8.20, which seems a bit outdated. The header (H5pubconf-32/H5pubconf-64) depends on wether you install the x86 or the x64 version of the package. Presumably to make it possible to install both packages at the same time. However, I just tried to install the x86 version and it failed due to a conflicting `H5public.h` which both versions provide.

Maybe it would make sense to also extend this PR to accommodate the x86 version also. But I'm not sure how relevant that is.
 
>     * Why does pkg-config method fail? Might be useful to know. Could you e.g. dump its output (from the build script) to check what it says?
> 

Running `cargo build` on master gives me:

```
error: failed to run custom build command for `hdf5-sys v0.5.1 (/home/julius/scratch/hdf5-rs/hdf5-sys)`
process didn't exit successfully: `/home/julius/scratch/hdf5-rs/target/debug/build/hdf5-sys-167b9658896931f0/build-script-build` (exit code: 101)
--- stdout
Attempting to find HDF5 via pkg-config...

--- stderr
thread 'main' panicked at 'Unable to locate HDF5 root directory and/or headers.', hdf5-sys/build.rs:513:13
```

Running `pkg-config hdf5` manually just gives me nothing and `pkg-config --list-all` does not contain any related entries.

**Pull request merged**
