### PR TITLE
Add hdf5 helper attribute with rename functionality

### LINKED ISSUE #201: Specify field names in compound types
I have an HDF5 dataset consisting of a 1D array of compound types, produced by astropy on a table with a `MaskedColumn`. The field name for the mask is "foo.mask", which does not seem to play nice with the derive macro. It would be useful to support something like:

```rust
#[derive(H5Type, Debug)]
#[repr(C)]
struct MyRow {
    foo: f64,
    #[hdf5(name = "foo.mask")]
    foo_mask: bool,
}

// ...

let array = dataset.read_1d::<MyRow>()?;
```

Apologies if this kind of thing is already supported and I didn't manage to find the right place in the documentation.

### PR DESCRIPTION
**Pull request by ajtribick**
Initial implementation of the helper attribute to allow field renaming. Resolves #201

### CODE REVIEW

**Comment by mulimoen** [comment]
This looks really great. It seems very straight forward to apply the same method to enums too if you change the call signature of `extract_field_name` to take `&[Attribute]` and return `Option<String>`. Feel free to add to the changelog too, this is a very useful feature.

**Review by mulimoen — APPROVED** [review]
Looks great, any objections against merging this @aldanor?

**Comment by ajtribick** [comment]
Any further changes needed here?

**Comment by mulimoen** [comment]
Looks great, thanks for the PR!

**Pull request merged**
