### PR TITLE
hdf5-sys: Fix wrong H5Z_filter_t type

### PR DESCRIPTION
**Pull request by kalcutter**
H5Z_filter_t has type int not hid_t.

### CODE REVIEW

**Comment by kalcutter** [comment]
This fixes `H5Zregister` and friends when building against hdf5 1.10.x which was broken because of this type mismatch.

**Comment by aldanor** [comment]
Well... https://github.com/aldanor/hdf5-rust/commit/11990985bd9dd17b6cb63a409c7d03537fadd8b5

Maybe just cherry-pick that one?

I really need to finish merging that mega-branch :(

**Comment by kalcutter** [comment]
Can you make a new bugfix release without the rest of the mega-branch? It would be helpful for the people using an official crates.io version.

**Comment by aldanor** [comment]
Good point, I can probably pull the first 30-ish commits or so from there - most of them being dependency version bumps, compatibility fixes, bugfixes like this one etc.

**Comment by aldanor** [comment]
@kalcutter I've pushed #79 with all changes unrelated to the mega-branch itself (including this fix). Something's failing there (because there's tons of stuff) but I don't have time to look at it in detail right now, looks like some obscure ndarray failures on appveyor :/

**Pull request closed without merging**
