### PR TITLE
hdf5-sys: Add HDF5 Optimized Functions

### PR DESCRIPTION
**Pull request by kalcutter**

### CODE REVIEW

**Comment by aldanor** [comment]
Thanks for the PR - interesting, how did I miss those. Are these part of the normal libhdf5 (and not libhdf5_hl), correct?

**Comment by aldanor** [comment]
https://support.hdfgroup.org/HDF5/doc/HL/RM_HDF5Optimized.html

Indeed, it seems like it's part of `libhdf5_hl`...

(Which means: if we do it, it should be done properly, i.e. either pull it all out into a separate crate or, at the very least, provide proper linking to `libhdf5_hl.so` on all platforms?)

**Comment by kalcutter** [comment]
Ahh. Sorry I didn't realize that these were in a separate library. Do you think its better to make another crate for the HL functions? It would be easier to put them in this crate (maybe behind a cfg gate)? Putting them in a separate crate would be more modular I suppose.

**Comment by kalcutter** [comment]
Thinking about this more... A new crate probably makes the most sense (hdf5-hl-sys?).

**Comment by magnusuMET** [comment]
In the static build (#67) I've combined the two libraries, with a feature flag to select "hl"

**Comment by kalcutter** [comment]
Something similar here does seem like the most pragmatic solution. Then we could directly reuse the code in build.rs (and other places). It would be less work/duplication.

**Comment by magnusuMET** [comment]
Would certainly be less problematic than trying to find compatible libraries across different versions of `hdf5-sys` and a `hdf5-hl-sys`

**Comment by kalcutter** [comment]
Closed in favor of #77.

**Pull request closed without merging**
